### ISSUE TITLE
Issue starting docker

### ISSUE THREAD

**Issue by akatreyt** [tonywagner/plugin.video.mlbserver#11]
trying to start the docker image tag [2024.7.23.4]

```
plugin.video.mlbserver  | Traceback (most recent call last):
plugin.video.mlbserver  |   File "/plugin.video.mlbserver/service.py", line 4, in <module>
plugin.video.mlbserver  |     Server()
plugin.video.mlbserver  |   File "/plugin.video.mlbserver/resources/lib/server.py", line 169, in __init__
plugin.video.mlbserver  |     server = ThreadedHTTPServer()
plugin.video.mlbserver  |              ^^^^^^^^^^^^^^^^^^^^
plugin.video.mlbserver  |   File "/plugin.video.mlbserver/resources/lib/server.py", line 146, in __init__
plugin.video.mlbserver  |     self.utils.server_init()
plugin.video.mlbserver  |   File "/plugin.video.mlbserver/resources/lib/utils.py", line 76, in server_init
plugin.video.mlbserver  |     set_default_settings(os.path.join(self.APP_DIRECTORY, 'resources', 'settings.xml'))
plugin.video.mlbserver  |     ^^^^^^^^^^^^^^^^^^^^
plugin.video.mlbserver  | NameError: name 'set_default_settings' is not defined
plugin.video.mlbserver exited with code 1
```

**Comment by akatreyt** [comment]
the fix is ...

utils.py #76

set_default_settings(os.path.join(self.APP_DIRECTORY, 'resources', 'settings.xml')) -> self.set_default_settings(os.path.join(self.APP_DIRECTORY, 'resources', 'settings.xml'))
