### ISSUE TITLE
m3u and xml capability

### ISSUE THREAD

**Issue by floppy-disk** [tonywagner/plugin.video.mlbserver#8]
Thanks for the great work on this update. I was wondering if you were considering building in the same ability to pull in the playlist and EPG as XML like mlbserver had or if this is being retired as part of the Kodi work. Just trying to decide where to spend my time getting things running again.

**Comment by tonywagner** [comment]
Working on M3U/XML today!

**Comment by SethL** [comment]
@tonywagner you will be a hero in the Channels DVR world when you release this.  There are already folks using the docker and inspecting the stream to get the m3u and manually setting up a custom channel per game.  You will also make my 80yr old mother's day when you do this.  I've been trying to explain about how api's have changed to someone who's life revolves around baseball lol.

**Comment by tonywagner** [comment]
I just pushed some MLB M3U/XML functionality in https://github.com/tonywagner/plugin.video.mlbserver/commit/1d67756df55eeb9b45296dcfd3ff37367d6c9331, if you want to test it. /mlb/channels.m3u and /mlb/guide.xml are the endpoints. (Minor league teams are listed but no games yet.)

**Comment by ahughes03** [comment]
I've updated but am getting the following error at start:

```
    cursor.execute('SELECT nickname FROM teams LIMIT 1')
sqlite3.OperationalError: no such table: teams
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/plugin.video.mlbserver/service.py", line 2, in <module>
    from resources.lib.server import Server
  File "/plugin.video.mlbserver/resources/lib/server.py", line 13, in <module>
    import resources.lib.utils as utils
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 322, in <module>
    initialize_cache_db()
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 144, in initialize_cache_db
    cursor.execute('DROP TABLE teams')
sqlite3.OperationalError: no such table: teams
Traceback (most recent call last):
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 142, in initialize_cache_db
    cursor.execute('SELECT nickname FROM teams LIMIT 1')
sqlite3.OperationalError: no such table: teams
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/plugin.video.mlbserver/service.py", line 2, in <module>
    from resources.lib.server import Server
  File "/plugin.video.mlbserver/resources/lib/server.py", line 13, in <module>
    import resources.lib.utils as utils
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 322, in <module>
    initialize_cache_db()
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 144, in initialize_cache_db
    cursor.execute('DROP TABLE teams')
sqlite3.OperationalError: no such table: teams
Traceback (most recent call last):
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 142, in initialize_cache_db
    cursor.execute('SELECT nickname FROM teams LIMIT 1')
sqlite3.OperationalError: no such table: teams
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/plugin.video.mlbserver/service.py", line 2, in <module>
    from resources.lib.server import Server
  File "/plugin.video.mlbserver/resources/lib/server.py", line 13, in <module>
    import resources.lib.utils as utils
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 322, in <module>
    initialize_cache_db()
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 144, in initialize_cache_db
    cursor.execute('DROP TABLE teams')
sqlite3.OperationalError: no such table: teams
Traceback (most recent call last):
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 142, in initialize_cache_d
    cursor.execute('SELECT nickname FROM teams LIMIT 1')
sqlite3.OperationalError: no such table: teams
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/plugin.video.mlbserver/service.py", line 2, in <module>
    from resources.lib.server import Server
  File "/plugin.video.mlbserver/resources/lib/server.py", line 13, in <module>
    import resources.lib.utils as utils
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 322, in <module>
    initialize_cache_db()
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 144, in initialize_cache_db
    cursor.execute('DROP TABLE teams')
sqlite3.OperationalError: no such table: teams
Traceback (most recent call last):
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 142, in initialize_cache_db
    cursor.execute('SELECT nickname FROM teams LIMIT 1')
sqlite3.OperationalError: no such table: teams
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/plugin.video.mlbserver/service.py", line 2, in <module>
    from resources.lib.server import Server
  File "/plugin.video.mlbserver/resources/lib/server.py", line 13, in <module>
    import resources.lib.utils as utils
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 322, in <module>
    initialize_cache_db()
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 144, in initialize_cache_db
    cursor.execute('DROP TABLE teams')
sqlite3.OperationalError: no such table: teams
Traceback (most recent call last):
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 142, in initialize_cache_db
    cursor.execute('SELECT nickname FROM teams LIMIT 1')
sqlite3.OperationalError: no such table: teams
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/plugin.video.mlbserver/service.py", line 2, in <module>
    from resources.lib.server import Server
  File "/plugin.video.mlbserver/resources/lib/server.py", line 13, in <module>
    import resources.lib.utils as utils
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 322, in <module>
    initialize_cache_db()
  File "/plugin.video.mlbserver/resources/lib/utils.py", line 144, in initialize_cache_db
    cursor.execute('DROP TABLE teams')
sqlite3.OperationalError: no such table: teams
```

**Comment by SethL** [comment]
> I just pushed some MLB M3U/XML functionality in [1d67756](https://github.com/tonywagner/plugin.video.mlbserver/commit/1d67756df55eeb9b45296dcfd3ff37367d6c9331), if you want to test it. /mlb/channels.m3u and /mlb/guide.xml are the endpoints. (Minor league teams are listed but no games yet.)

Working great for me thanks!

**Comment by tonywagner** [comment]
> I've updated but am getting the following error at start (this is in a Docker container, I tried with persistent and stateless data folders).

I just pushed another update that should fix that.

**Comment by ahughes03** [comment]
> > I've updated but am getting the following error at start (this is in a Docker container, I tried with persistent and stateless data folders).
> 
> I just pushed another update that should fix that.

Docker container is up and running, thanks!!!

**Comment by ahughes03** [comment]
New error when testing the XML:

```
[ERROR] XML syntax error on line 615: invalid character entity &home_teamId (no semicolon) () - EC: 0
```

I'm not getting actual guide entries and I'm assuming this could be a potential cause.

**Comment by ahughes03** [comment]
Guide entries are working in `v2024.7.23+omega.4`. Thanks for the fix.

**Comment by justinhorner** [comment]
M3U and EPG xml are working great for me, using Docker container.

Both TV and radio audio also working!

Thank you!

**Comment by tonywagner** [comment]
mlbserver is now working again too

**Comment by justinhorner** [comment]
> mlbserver is now working again too

Do you have an idea of which project you’ll focus on moving forward? Was the fix to the JS mlbserver intended to make it compatible and future features would be focused on this project?

thanks for all the work, I only discovered the JS project recently and really like having my mlbtv service (via the m3u and epg xml) available with my other iptv services and all accessible in a single client.

**Comment by tonywagner** [comment]
> Do you have an idea of which project you’ll focus on moving forward? Was the fix to the JS mlbserver intended to make it compatible and future features would be focused on this project?

That was the idea, but I don't expect to make a whole lot of near future progress on this one. But I'm open to pull requests, and the code of the new project is hopefully a bit more intuitive to outsiders.
